name: test2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  google_maps_flutter: ^2.9.0
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.2
  logger: ^2.3.0
  web_socket_channel: ^3.0.1
  fluttertoast: ^8.0.8
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6

  # Firebase packages
  firebase_core: ^3.3.0
  geolocator: ^12.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  workmanager: ^0.5.2
  google_maps_cluster_manager: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11
  flutter_bloc: ^8.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/loading_image.png
    - assets/login_background.png
    - assets/background.png
    - assets/SN Logo.jpg
    - assets/images/background.jpg
    - assets/images/season.jpg
    - assets/images/region.jpg
    - assets/images/team_album.jpg
    - assets/cat.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
