name: test2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0
  path_provider: ^2.0.11
  http: ^1.2.2
  cloud_firestore: ^5.0.0  #
  firebase_auth: ^5.0.0    #
  google_maps_flutter: ^2.0.6
  flutter_screenutil: ^5.9.0
  image_picker: ^0.8.4+4
  logger: ^2.3.0
  web_socket_channel: ^3.0.1
  fluttertoast: ^8.0.8
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  permission_handler: ^10.2.0

  # Firebase packages
  firebase_core: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0 # Added flutter_launcher_icons
  build_runner: ^2.1.8  # 최신 버전을 사용하세요.
  flutter_bloc: ^8.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/loading_image.png
    - assets/login_background.png
    - assets/background.png #지장없으면 지워도 됨
    - assets/SN Logo.jpg
    - assets/images/background.jpg
    - assets/images/season.jpg
    - assets/images/region.jpg
    - assets/images/team_album.jpg
    - assets/cat.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true