name: test2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  flutter_screenutil: ^5.9.0
  image_picker: ^0.8.4+4
  logger: ^2.3.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading_image.png
    - assets/login_background.png
    - assets/SN Logo.jpg
